# Generated by Django 4.2.4 on 2023-09-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
